version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - node_modules:/app/frontend/node_modules
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    tty: true
    env_file: ./frontend/.env.development
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/frontend/node_modules
    depends_on:
      - backend
volumes:
  node_modules:
