name: Docker Image CI

on:
  push:

jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-node@v2
