name: Normal CI

on:
  push:

jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install yarn
        working-directory: ./frontend
        run: npm install -g yarn
      - name: Install yarn packages
        working-directory: ./frontend
        run: yarn install
      - name: Install pip packages
        working-directory: ./backend
        run: python -m pip install -r requirements.txt
      - name: pre commit run
        uses: pre-commit/action@v2.0.3
